### ISSUE TITLE
init app with koa and typescript

### ISSUE THREAD

**Issue by dantas15** [dantas15/todo-graphql-koa-relay#6]

**Comment by gustav0d** [comment]
use existing tsconfig from #2

**Comment by gustav0d** [comment]
- koa with graphql: https://github.com/graphql-community/koa-graphql

**Comment by gustav0d** [comment]
- koa introduction: https://koajs.com/#introduction

**Comment by gustav0d** [comment]
- koa examples: https://github.com/koajs/examples

**Comment by gustav0d** [comment]
- path-mapping in typescript: https://blog.rocketseat.com.br/path-mapping-typescript/

**Comment by gustav0d** [comment]
solved in [`746a9a9`](https://github.com/dantas15/todo-graphql-koa-relay/commit/746a9a914acfa575e5d5a1fd755feaa389872fd1)
